name: Android CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Git user identity
        run: |
          git config --global user.email "la.niina.me@gmail.com"
          git config --global user.name "la-niina"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and tag version
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
          versionName=$(grep "versionName" app/build.gradle.kts | grep -o "\"[^\"]*\"" | tr -d '"')
          echo "Version Name: $versionName"
          git tag -a "v$versionName" -m "Release version $versionName"
          git push --tags

      - name: Generate release notes
        uses: Decathlon/release-notes-generator-action@v3.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
