name: Android CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git user identity
        run: |
          git config --global user.email "la.niina.me@gmail.com"
          git config --global user.name "la-niina"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Google Cloud AI
        run: |
          chmod +x gradlew
          curl -O https://storage.googleapis.com/generativeai-downloads/clients/google-cloud-ai-generativelanguage-v1beta2-java.tar.gz
          tar -xzvf google-cloud-ai-generativelanguage-v1beta2-java.tar.gz
          cd google-cloud-ai-generativelanguage-v1beta2-java
          ./gradlew publishToMavenLocal

      - name: Build and tag version
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
          versionName=$(grep "versionName" app/build.gradle.kts | grep -o "\"[^\"]*\"" | tr -d '"')
          echo "Version Name: $versionName"
          git tag -a "v$versionName" -m "Release version $versionName"
          git push --tags

      - name: Rename release directory
        run: |
          mv app/build/outputs/apk/release/metospherus-arm64-v8a-release.apk app/build/outputs/apk/release/metospherus-arm64-v8a.apk
          mv app/build/outputs/apk/release/metospherus-armeabi-v7a-release.apk app/build/outputs/apk/release/metospherus-armeabi-v7a.apk
          mv app/build/outputs/apk/release/metospherus-x86-release.apk app/build/outputs/apk/release/metospherus-x86.apk
          mv app/build/outputs/apk/release/metospherus-x86_64-release.apk app/build/outputs/apk/release/metospherus-x86_64.apk

      - name: Create Draft Release
        id: create_draft_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: app/build/outputs/apk/release/metospherus*
          draft: true
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            # Metospherus A Comprehensive Medical System
            **What's New** 
            - We included a number of updates
            - Modules , documents , preview
            - documentation , profile etc
            - Language model fixing bugs 
            - Developing as you use 

            # Developers
            @la-niina by @Moluccus-inc/moluccus Founder and soul developer
