name: Android CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Git user identity
        run: |
          git config --global user.email "la.niina.me@gmail.com"
          git config --global user.name "la-niina"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build and tag version
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
          versionName=$(grep "versionName" app/build.gradle.kts | grep -o "\"[^\"]*\"" | tr -d '"')
          echo "Version Name: $versionName"
          git tag -a "v$versionName" -m "Release version $versionName"
          git push --tags

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: metospherus.apk
          path: app/build/outputs/apk/release/metospherus-release.apk