name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'
          
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Build and tag version
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease
          versionCode=$(grep "versionCode" app/build.gradle | grep -o "[0-9]*")
          echo "Version Code: $versionCode"
          git tag -a "v$versionCode" -m "Release version $versionCode"
          git push --tags
